import jsPDF from 'jspdf';
import type { AnalysisResult, OptimizedResume, ExperienceEntry, EducationEntry, CertificationEntry, ProjectEntry } from '../types';

// ============================================================
// TYPOGRAPHY & STYLING CONSTANTS
// ============================================================

const FONTS = {
  regular: 'helvetica',
  bold: 'helvetica',
  italic: 'helvetica',
} as const;

const COLORS = {
  primary: [37, 99, 235] as [number, number, number],
  primaryDark: [29, 78, 216] as [number, number, number],
  accent: [147, 51, 234] as [number, number, number],
  green: [22, 163, 74] as [number, number, number],
  greenLight: [240, 253, 244] as [number, number, number],
  red: [220, 38, 38] as [number, number, number],
  redLight: [254, 242, 242] as [number, number, number],
  orange: [251, 146, 60] as [number, number, number],
  gray50: [249, 250, 251] as [number, number, number],
  gray100: [243, 244, 246] as [number, number, number],
  gray200: [229, 231, 235] as [number, number, number],
  gray400: [156, 163, 175] as [number, number, number],
  gray500: [107, 114, 128] as [number, number, number],
  gray600: [75, 85, 99] as [number, number, number],
  gray700: [55, 65, 81] as [number, number, number],
  gray800: [31, 41, 55] as [number, number, number],
  gray900: [17, 24, 39] as [number, number, number],
  white: [255, 255, 255] as [number, number, number],
  black: [0, 0, 0] as [number, number, number],
};

const MARGIN = 20;
const PAGE_WIDTH = 210;
const PAGE_HEIGHT = 297;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

// ============================================================
// PDF UTILITY FUNCTIONS
// ============================================================

function createDoc(): jsPDF {
  return new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
    compress: true,
  });
}

function addDivider(doc: jsPDF, y: number, color: [number, number, number] = COLORS.gray200): number {
  doc.setDrawColor(color[0], color[1], color[2]);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  return y + 3;
}

function checkPage(doc: jsPDF, y: number, neededSpace: number = 20): number {
  if (y + neededSpace > PAGE_HEIGHT - 25) {
    doc.addPage();
    return MARGIN;
  }
  return y;
}

function addFooter(doc: jsPDF, pageNum: number, totalPages: number, title: string) {
  const y = PAGE_HEIGHT - 10;
  doc.setFontSize(7);
  doc.setTextColor(COLORS.gray400[0], COLORS.gray400[1], COLORS.gray400[2]);
  doc.setFont(FONTS.regular, 'normal');

  doc.setDrawColor(COLORS.gray200[0], COLORS.gray200[1], COLORS.gray200[2]);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y - 2, PAGE_WIDTH - MARGIN, y - 2);

  doc.text(title, MARGIN, y + 2);
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_WIDTH - MARGIN, y + 2, { align: 'right' });
  doc.text('Generated by ATS Resume Analyzer', PAGE_WIDTH / 2, y + 2, { align: 'center' });
}

function addSectionHeader(doc: jsPDF, y: number, title: string, color: [number, number, number] = COLORS.primary): { y: number } {
  y = checkPage(doc, y, 15);
  y += 3;

  doc.setFillColor(color[0], color[1], color[2]);
  doc.rect(MARGIN, y - 4, CONTENT_WIDTH, 8, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont(FONTS.bold, 'bold');
  doc.text(title.toUpperCase(), MARGIN + 4, y + 1);

  return { y: y + 10 };
}

function addWrappedText(doc: jsPDF, y: number, text: string, opts: {
  fontSize?: number;
  font?: string;
  fontStyle?: string;
  color?: [number, number, number];
  indent?: number;
  lineSpacing?: number;
  maxWidth?: number;
} = {}): number {
  const {
    fontSize = 9,
    font = FONTS.regular,
    fontStyle = 'normal',
    color = COLORS.gray800,
    indent = 0,
    lineSpacing = 4.5,
    maxWidth = CONTENT_WIDTH - indent,
  } = opts;

  doc.setFontSize(fontSize);
  doc.setFont(font, fontStyle);
  doc.setTextColor(color[0], color[1], color[2]);

  const lines = doc.splitTextToSize(text, maxWidth);
  lines.forEach((line: string) => {
    y = checkPage(doc, y, lineSpacing);
    doc.text(line, MARGIN + indent, y);
    y += lineSpacing;
  });

  return y;
}

function addBullet(doc: jsPDF, y: number, text: string, opts: {
  fontSize?: number;
  color?: [number, number, number];
  bulletChar?: string;
  indent?: number;
  lineSpacing?: number;
} = {}): number {
  const {
    fontSize = 9,
    color = COLORS.gray800,
    bulletChar = '\u2022',
    indent = 6,
    lineSpacing = 4.5,
  } = opts;

  doc.setFontSize(fontSize);
  doc.setFont(FONTS.regular, 'normal');

  const bulletWidth = doc.getTextWidth(bulletChar + ' ');
  const maxWidth = CONTENT_WIDTH - indent - bulletWidth - 2;
  const lines = doc.splitTextToSize(text, maxWidth);

  lines.forEach((line: string, idx: number) => {
    y = checkPage(doc, y, lineSpacing);
    if (idx === 0) {
      doc.setTextColor(COLORS.gray500[0], COLORS.gray500[1], COLORS.gray500[2]);
      doc.text(bulletChar, MARGIN + indent, y);
      doc.setTextColor(color[0], color[1], color[2]);
      doc.text(line, MARGIN + indent + bulletWidth + 1, y);
    } else {
      doc.setTextColor(color[0], color[1], color[2]);
      doc.text(line, MARGIN + indent + bulletWidth + 1, y);
    }
    y += lineSpacing;
  });

  return y;
}

function addScoreCircle(doc: jsPDF, cx: number, cy: number, score: number, radius: number = 18) {
  const color: [number, number, number] =
    score >= 80 ? COLORS.green : score >= 60 ? COLORS.orange : COLORS.red;

  doc.setDrawColor(COLORS.gray200[0], COLORS.gray200[1], COLORS.gray200[2]);
  doc.setLineWidth(0.5);
  doc.circle(cx, cy, radius, 'S');

  doc.setFillColor(color[0], color[1], color[2]);
  doc.circle(cx, cy, radius - 2, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont(FONTS.bold, 'bold');
  doc.text(score.toFixed(0), cx, cy + 1, { align: 'center' });

  doc.setFontSize(7);
  doc.setFont(FONTS.regular, 'normal');
  doc.text('/ 100', cx, cy + 8, { align: 'center' });
}

function addProgressBar(doc: jsPDF, y: number, label: string, value: number, max: number, barWidth: number = 80) {
  const percentage = (value / max) * 100;
  const barColor: [number, number, number] =
    percentage >= 80 ? COLORS.green : percentage >= 60 ? COLORS.orange : COLORS.red;

  doc.setFontSize(8);
  doc.setFont(FONTS.bold, 'bold');
  doc.setTextColor(COLORS.gray700[0], COLORS.gray700[1], COLORS.gray700[2]);
  doc.text(label, MARGIN, y);

  doc.setFont(FONTS.regular, 'normal');
  doc.setTextColor(COLORS.gray500[0], COLORS.gray500[1], COLORS.gray500[2]);
  doc.text(`${value.toFixed(1)} / ${max}`, MARGIN + 65, y);

  const barX = MARGIN + 95;
  const barY = y - 3;
  const barHeight = 4;

  doc.setFillColor(COLORS.gray200[0], COLORS.gray200[1], COLORS.gray200[2]);
  doc.roundedRect(barX, barY, barWidth, barHeight, 1.5, 1.5, 'F');

  doc.setFillColor(barColor[0], barColor[1], barColor[2]);
  const fillWidth = (barWidth * percentage) / 100;
  if (fillWidth > 0) {
    doc.roundedRect(barX, barY, fillWidth, barHeight, 1.5, 1.5, 'F');
  }

  doc.setFontSize(7);
  doc.setFont(FONTS.regular, 'normal');
  doc.setTextColor(COLORS.gray500[0], COLORS.gray500[1], COLORS.gray500[2]);
  doc.text(`${percentage.toFixed(0)}%`, barX + barWidth + 3, y + 0.5);
}

function getScoreColor(score: number): [number, number, number] {
  if (score >= 80) return COLORS.green;
  if (score >= 60) return COLORS.orange;
  return COLORS.red;
}

// ============================================================
// PDF 1: PROFESSIONAL OPTIMIZED RESUME PDF
// ============================================================

export function generateResumePDF(
  optimizedResume: OptimizedResume,
  mode: string = 'balanced'
) {
  const doc = createDoc();
  let y = MARGIN;

  // ===== HEADER =====
  doc.setFillColor(COLORS.primaryDark[0], COLORS.primaryDark[1], COLORS.primaryDark[2]);
  doc.rect(0, 0, PAGE_WIDTH, 35, 'F');

  doc.setFillColor(COLORS.accent[0], COLORS.accent[1], COLORS.accent[2]);
  doc.rect(0, 35, PAGE_WIDTH, 2, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont(FONTS.bold, 'bold');
  doc.text('Optimized Resume', PAGE_WIDTH / 2, 18, { align: 'center' });

  doc.setFontSize(8);
  doc.setFont(FONTS.regular, 'normal');
  const modeLabel = mode.charAt(0).toUpperCase() + mode.slice(1);
  doc.text(
    `Mode: ${modeLabel} | Predicted ATS Score: ${optimizedResume.predictedScore.toFixed(0)}/100 | ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    PAGE_WIDTH / 2, 28, { align: 'center' }
  );

  y = 42;

  // Professional Summary
  if (optimizedResume.professionalSummary) {
    const section = addSectionHeader(doc, y, 'Professional Summary', COLORS.primary);
    y = section.y;
    y = addWrappedText(doc, y, optimizedResume.professionalSummary, {
      fontSize: 9, fontStyle: 'normal', lineSpacing: 4.5, indent: 2,
    });
    y += 2;
  }

  // Skills
  if (optimizedResume.skills.length > 0) {
    const section = addSectionHeader(doc, y, 'Skills', COLORS.primary);
    y = section.y;

    const skillFontSize = 8;
    doc.setFontSize(skillFontSize);
    doc.setFont(FONTS.bold, 'bold');
    const maxLineWidth = CONTENT_WIDTH - 4;
    const line: string[] = [];
    let lineWidth = 0;

    optimizedResume.skills.forEach((skill, idx) => {
      const separator = idx < optimizedResume.skills.length - 1 ? ', ' : '';
      const text = skill + separator;
      const w = doc.getTextWidth(text);

      if (lineWidth + w > maxLineWidth && line.length > 0) {
        y = checkPage(doc, y, 6);
        doc.setTextColor(COLORS.gray800[0], COLORS.gray800[1], COLORS.gray800[2]);
        doc.text(line.join(''), MARGIN + 2, y);
        y += 6;
        line.length = 0;
        lineWidth = 0;
      }
      line.push(text);
      lineWidth += w;
    });

    if (line.length > 0) {
      y = checkPage(doc, y, 6);
      doc.setTextColor(COLORS.gray800[0], COLORS.gray800[1], COLORS.gray800[2]);
      doc.text(line.join(''), MARGIN + 2, y);
      y += 6;
    }
    y += 1;
  }

  // Experience
  if (optimizedResume.experience.length > 0) {
    const section = addSectionHeader(doc, y, 'Experience', COLORS.primary);
    y = section.y;

    optimizedResume.experience.forEach((exp: ExperienceEntry) => {
      y = checkPage(doc, y, 20);

      doc.setFontSize(10);
      doc.setFont(FONTS.bold, 'bold');
      doc.setTextColor(COLORS.gray900[0], COLORS.gray900[1], COLORS.gray900[2]);
      doc.text(`${exp.title} at ${exp.company}`, MARGIN + 2, y);
      y += 5;

      doc.setFontSize(8);
      doc.setFont(FONTS.regular, 'normal');
      doc.setTextColor(COLORS.gray500[0], COLORS.gray500[1], COLORS.gray500[2]);
      let dateLocation = exp.dates;
      if (exp.location) dateLocation += ` | ${exp.location}`;
      doc.text(dateLocation, MARGIN + 2, y);
      y += 5;

      exp.bullets.forEach((bullet: string) => {
        y = addBullet(doc, y, bullet, { fontSize: 9, color: COLORS.gray800, indent: 2, lineSpacing: 4.5 });
      });

      if (exp.technologies && exp.technologies.length > 0) {
        y += 1;
        doc.setFontSize(7);
        doc.setFont(FONTS.italic, 'italic');
        doc.setTextColor(COLORS.gray400[0], COLORS.gray400[1], COLORS.gray400[2]);
        doc.text(`Technologies: ${exp.technologies.join(', ')}`, MARGIN + 8, y);
        y += 4;
      }
      y += 2;
    });
  }

  // Education
  if (optimizedResume.education.length > 0) {
    const section = addSectionHeader(doc, y, 'Education', COLORS.primary);
    y = section.y;

    optimizedResume.education.forEach((edu: EducationEntry) => {
      y = checkPage(doc, y, 12);

      doc.setFontSize(9);
      doc.setFont(FONTS.bold, 'bold');
      doc.setTextColor(COLORS.gray900[0], COLORS.gray900[1], COLORS.gray900[2]);
      let eduLine = edu.degree;
      if (edu.field) eduLine += ` in ${edu.field}`;
      doc.text(eduLine, MARGIN + 2, y);
      y += 4.5;

      doc.setFontSize(8);
      doc.setFont(FONTS.regular, 'normal');
      doc.setTextColor(COLORS.gray600[0], COLORS.gray600[1], COLORS.gray600[2]);
      let instLine = edu.institution;
      if (edu.dates) instLine += ` | ${edu.dates}`;
      if (edu.gpa) instLine += ` | GPA: ${edu.gpa}`;
      doc.text(instLine, MARGIN + 2, y);
      y += 4.5;

      if (edu.honors && edu.honors.length > 0) {
        doc.setFontSize(7);
        doc.setFont(FONTS.italic, 'italic');
        doc.setTextColor(COLORS.gray500[0], COLORS.gray500[1], COLORS.gray500[2]);
        doc.text(`Honors: ${edu.honors.join(', ')}`, MARGIN + 2, y);
        y += 3;
      }
      y += 2;
    });
  }

  // Certifications
  if (optimizedResume.certifications.length > 0) {
    const section = addSectionHeader(doc, y, 'Certifications', COLORS.primary);
    y = section.y;

    optimizedResume.certifications.forEach((cert: CertificationEntry) => {
      y = checkPage(doc, y, 8);

      doc.setFontSize(9);
      doc.setFont(FONTS.bold, 'bold');
      doc.setTextColor(COLORS.gray800[0], COLORS.gray800[1], COLORS.gray800[2]);
      doc.text(cert.name, MARGIN + 2, y);
      y += 4.5;

      doc.setFontSize(8);
      doc.setFont(FONTS.regular, 'normal');
      doc.setTextColor(COLORS.gray500[0], COLORS.gray500[1], COLORS.gray500[2]);
      let certLine = '';
      if (cert.issuer) certLine += cert.issuer;
      if (cert.date) certLine += certLine ? ` | ${cert.date}` : cert.date;
      if (cert.credentialId) certLine += certLine ? ` | ID: ${cert.credentialId}` : `ID: ${cert.credentialId}`;
      if (certLine) doc.text(certLine, MARGIN + 2, y);
      y += 4;
      y += 1;
    });
  }

  // Projects
  if (optimizedResume.projects.length > 0) {
    const section = addSectionHeader(doc, y, 'Projects', COLORS.primary);
    y = section.y;

    optimizedResume.projects.forEach((proj: ProjectEntry) => {
      y = checkPage(doc, y, 12);

      doc.setFontSize(9);
      doc.setFont(FONTS.bold, 'bold');
      doc.setTextColor(COLORS.gray900[0], COLORS.gray900[1], COLORS.gray900[2]);
      doc.text(proj.name, MARGIN + 2, y);
      y += 4.5;

      if (proj.description) {
        y = addWrappedText(doc, y, proj.description, {
          fontSize: 8, color: COLORS.gray600, indent: 2, lineSpacing: 4,
        });
      }

      if (proj.technologies.length > 0) {
        doc.setFontSize(7);
        doc.setFont(FONTS.italic, 'italic');
        doc.setTextColor(COLORS.gray400[0], COLORS.gray400[1], COLORS.gray400[2]);
        doc.text(`Technologies: ${proj.technologies.join(', ')}`, MARGIN + 8, y);
        y += 3.5;
      }

      proj.bullets.forEach((bullet: string) => {
        y = addBullet(doc, y, bullet, { fontSize: 8, color: COLORS.gray700, indent: 2, lineSpacing: 4 });
      });
      y += 2;
    });
  }

  // Footers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages, 'ATS Resume Analyzer - Optimized Resume');
  }

  const fileName = `optimized-resume-${mode}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}

// ============================================================
// PDF 2: ATS ANALYSIS REPORT PDF
// ============================================================

export function generatePDFReport(
  results: AnalysisResult,
  optimizedResume?: OptimizedResume,
  optimizationMode?: string
) {
  const doc = createDoc();
  let y = MARGIN;

  // ===== HEADER =====
  doc.setFillColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  doc.rect(0, 0, PAGE_WIDTH, 38, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont(FONTS.bold, 'bold');
  doc.text('ATS Resume Analysis Report', PAGE_WIDTH / 2, 16, { align: 'center' });

  doc.setFontSize(9);
  doc.setFont(FONTS.regular, 'normal');
  const reportDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });
  doc.text(reportDate, PAGE_WIDTH / 2, 27, { align: 'center' });

  y = 48;

  // ===== OVERALL SCORE =====
  const scoreSection = addSectionHeader(doc, y, 'Overall ATS Score', COLORS.primary);
  y = scoreSection.y;

  const circleX = PAGE_WIDTH / 2;
  const circleY = y + 20;
  addScoreCircle(doc, circleX, circleY, results.score);
  y = circleY + 25;

  const message =
    results.score >= 80
      ? '✅ Excellent! Your resume is well-optimized for ATS systems. Recruiters will easily find your qualifications.'
      : results.score >= 60
      ? '👍 Good score! With a few targeted improvements, your resume can rank even higher with ATS systems.'
      : '📈 There is significant room for improvement. Follow the recommendations below to boost your ATS compatibility.';

  y = checkPage(doc, y, 10);
  doc.setFontSize(9);
  doc.setFont(FONTS.italic, 'italic');
  doc.setTextColor(COLORS.gray600[0], COLORS.gray600[1], COLORS.gray600[2]);
  const msgLines = doc.splitTextToSize(message, CONTENT_WIDTH - 10);
  msgLines.forEach((line: string) => {
    doc.text(line, PAGE_WIDTH / 2, y, { align: 'center' });
    y += 5;
  });
  y += 3;

  // ===== PREDICTED OPTIMIZED SCORE =====
  if (optimizedResume) {
    const optSection = addSectionHeader(doc, y, 'AI Optimization Result', COLORS.accent);
    y = optSection.y;

    doc.setFillColor(COLORS.accent[0], COLORS.accent[1], COLORS.accent[2]);
    doc.roundedRect(MARGIN, y - 3, 50, 6, 2, 2, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7);
    doc.setFont(FONTS.bold, 'bold');
    doc.text(`Mode: ${(optimizationMode || 'balanced').toUpperCase()}`, MARGIN + 25, y + 0.5, { align: 'center' });
    y += 9;

    // Score comparison
    const origColor = getScoreColor(results.score);
    doc.setTextColor(origColor[0], origColor[1], origColor[2]);
    doc.setFontSize(28);
    doc.setFont(FONTS.bold, 'bold');
    doc.text(results.score.toFixed(0), MARGIN + 25, y + 8, { align: 'center' });
    doc.setFontSize(8);
    doc.setFont(FONTS.regular, 'normal');
    doc.setTextColor(COLORS.gray500[0], COLORS.gray500[1], COLORS.gray500[2]);
    doc.text('Original Score', MARGIN + 25, y + 14, { align: 'center' });

    doc.setFontSize(18);
    doc.setTextColor(COLORS.accent[0], COLORS.accent[1], COLORS.accent[2]);
    doc.text('\u2192', PAGE_WIDTH / 2, y + 9, { align: 'center' });

    doc.setFontSize(10);
    doc.setTextColor(COLORS.green[0], COLORS.green[1], COLORS.green[2]);
    doc.text(`+${optimizedResume.improvementPercentage.toFixed(0)}%`, PAGE_WIDTH / 2, y + 15, { align: 'center' });

    const optColor = getScoreColor(optimizedResume.predictedScore);
    doc.setTextColor(optColor[0], optColor[1], optColor[2]);
    doc.setFontSize(28);
    doc.setFont(FONTS.bold, 'bold');
    doc.text(optimizedResume.predictedScore.toFixed(0), PAGE_WIDTH - MARGIN - 25, y + 8, { align: 'center' });
    doc.setFontSize(8);
    doc.setFont(FONTS.regular, 'normal');
    doc.setTextColor(COLORS.gray500[0], COLORS.gray500[1], COLORS.gray500[2]);
    doc.text('Optimized Score', PAGE_WIDTH - MARGIN - 25, y + 14, { align: 'center' });

    y += 22;

    // Score improvement bar
    y = checkPage(doc, y, 15);
    const barTotalWidth = CONTENT_WIDTH;
    doc.setFillColor(COLORS.gray200[0], COLORS.gray200[1], COLORS.gray200[2]);
    doc.roundedRect(MARGIN, y, barTotalWidth, 6, 2, 2, 'F');

    const origBarX = MARGIN + (barTotalWidth * (results.score / 100));
    const optBarX = MARGIN + (barTotalWidth * (optimizedResume.predictedScore / 100));

    if (optBarX > origBarX) {
      doc.setFillColor(COLORS.green[0], COLORS.green[1], COLORS.green[2]);
      doc.roundedRect(origBarX, y, optBarX - origBarX, 6, 2, 2, 'F');
    }

    doc.setFillColor(origColor[0], origColor[1], origColor[2]);
    doc.circle(origBarX, y + 3, 3, 'F');
    doc.setTextColor(origColor[0], origColor[1], origColor[2]);
    doc.setFontSize(6);
    doc.text(results.score.toFixed(0), origBarX, y + 12, { align: 'center' });

    doc.setFillColor(optColor[0], optColor[1], optColor[2]);
    doc.circle(optBarX, y + 3, 3, 'F');
    doc.setTextColor(optColor[0], optColor[1], optColor[2]);
    doc.setFontSize(6);
    doc.text(optimizedResume.predictedScore.toFixed(0), optBarX, y + 12, { align: 'center' });

    y += 18;
  }

  // ===== SCORE BREAKDOWN =====
  if (results.breakdown) {
    const breakdownSection = addSectionHeader(doc, y, 'Score Breakdown', COLORS.primary);
    y = breakdownSection.y;

    const items = [
      { label: 'Keyword Match', score: results.breakdown.keywordMatch, max: 40 },
      { label: 'Skill Alignment', score: results.breakdown.skillAlignment, max: 25 },
      { label: 'Experience Match', score: results.breakdown.experienceMatch, max: 15 },
      { label: 'Formatting', score: results.breakdown.formatting, max: 10 },
      { label: 'Readability', score: results.breakdown.readability, max: 10 },
    ];

    items.forEach((item) => {
      y = checkPage(doc, y, 12);
      addProgressBar(doc, y, item.label, item.score, item.max);
      y += 9;
    });
    y += 2;
  }

  // ===== ADVANCED ANALYSIS =====
  if (optimizedResume?.analysis) {
    const advSection = addSectionHeader(doc, y, 'Advanced ATS Analysis', [16, 185, 129]);
    y = advSection.y;

    const metrics = [
      { label: 'Keyword Density', value: `${optimizedResume.analysis.keywordDensity.toFixed(1)}%`, target: 'Target: 2-5%' },
      { label: 'Readability', value: `${optimizedResume.analysis.readabilityScore.toFixed(0)}/100`, target: 'Higher is better' },
      { label: 'Action Verbs', value: `${optimizedResume.analysis.actionVerbScore.toFixed(0)}%`, target: '% strong verbs' },
      { label: 'Weak Bullets', value: `${optimizedResume.analysis.weakBullets.length}`, target: 'Ideally 0' },
    ];

    const cardW = (CONTENT_WIDTH - 8) / 2;
    const cardH = 18;

    metrics.forEach((metric, idx) => {
      const col = idx % 2;
      const row = Math.floor(idx / 2);
      const cardX = MARGIN + col * (cardW + 8);
      const cardY = y + row * (cardH + 6);

      doc.setFillColor(COLORS.greenLight[0], COLORS.greenLight[1], COLORS.greenLight[2]);
      doc.roundedRect(cardX, cardY, cardW, cardH, 3, 3, 'F');

      doc.setFontSize(18);
      doc.setFont(FONTS.bold, 'bold');
      doc.setTextColor(COLORS.green[0], COLORS.green[1], COLORS.green[2]);
      doc.text(metric.value, cardX + cardW / 2, cardY + 8, { align: 'center' });

      doc.setFontSize(8);
      doc.setFont(FONTS.regular, 'normal');
      doc.setTextColor(COLORS.gray600[0], COLORS.gray600[1], COLORS.gray600[2]);
      doc.text(metric.label, cardX + cardW / 2, cardY + 14, { align: 'center' });

      doc.setFontSize(6);
      doc.setTextColor(COLORS.gray400[0], COLORS.gray400[1], COLORS.gray400[2]);
      doc.text(metric.target, cardX + cardW / 2, cardY + cardH - 1, { align: 'center' });
    });

    y += 2 * (cardH + 6) + 5;

    // Section Completeness
    if (optimizedResume.analysis.sectionCompleteness) {
      y = checkPage(doc, y, 20);
      doc.setFontSize(9);
      doc.setFont(FONTS.bold, 'bold');
      doc.setTextColor(COLORS.gray700[0], COLORS.gray700[1], COLORS.gray700[2]);
      doc.text('Section Completeness', MARGIN, y);
      y += 5;

      const completeness = Object.entries(optimizedResume.analysis.sectionCompleteness);
      const compCardW = (CONTENT_WIDTH - 12) / 4;

      completeness.forEach(([section, complete]) => {
        const cardX = MARGIN + (0 * (compCardW + 4));
        doc.setFillColor(
          complete ? COLORS.greenLight[0] : COLORS.redLight[0],
          complete ? COLORS.greenLight[1] : COLORS.redLight[1],
          complete ? COLORS.greenLight[2] : COLORS.redLight[2]
        );
        doc.roundedRect(cardX, y, compCardW, 14, 2, 2, 'F');

        doc.setFontSize(7);
        doc.setFont(FONTS.bold, 'bold');
        doc.setTextColor(
          complete ? COLORS.green[0] : COLORS.red[0],
          complete ? COLORS.green[1] : COLORS.red[1],
          complete ? COLORS.green[2] : COLORS.red[2]
        );
        doc.text(section.charAt(0).toUpperCase() + section.slice(1), cardX + compCardW / 2, y + 5, { align: 'center' });

        doc.setFontSize(6);
        doc.setFont(FONTS.regular, 'normal');
        doc.text(complete ? '\u2713 Complete' : '\u2717 Missing', cardX + compCardW / 2, y + 11, { align: 'center' });
      });

      y += 20;
    }
  }

  // ===== MATCHED SKILLS =====
  if (results.matchedSkills.length > 0) {
    const section = addSectionHeader(doc, y, 'Matched Skills', COLORS.green);
    y = section.y;

    doc.setFontSize(8);
    doc.setFont(FONTS.regular, 'normal');
    doc.setTextColor(COLORS.gray800[0], COLORS.gray800[1], COLORS.gray800[2]);

    const skillsText = results.matchedSkills.join('  \u2022  ');
    const lines = doc.splitTextToSize(skillsText, CONTENT_WIDTH - 4);
    lines.forEach((line: string) => {
      y = checkPage(doc, y, 5);
      doc.text(line, MARGIN + 2, y);
      y += 5;
    });
    y += 2;
  }

  // ===== MISSING SKILLS =====
  if (results.missingSkills.length > 0) {
    const section = addSectionHeader(doc, y, 'Missing Skills', COLORS.red);
    y = section.y;

    doc.setFontSize(8);
    doc.setFont(FONTS.regular, 'normal');
    doc.setTextColor(COLORS.gray800[0], COLORS.gray800[1], COLORS.gray800[2]);

    const skillsText = results.missingSkills.join('  \u2022  ');
    const lines = doc.splitTextToSize(skillsText, CONTENT_WIDTH - 4);
    lines.forEach((line: string) => {
      y = checkPage(doc, y, 5);
      doc.text(line, MARGIN + 2, y);
      y += 5;
    });
    y += 2;
  }

  // ===== ADDED KEYWORDS =====
  if (optimizedResume?.addedKeywords && optimizedResume.addedKeywords.length > 0) {
    const section = addSectionHeader(doc, y, 'Keywords Added by AI', [99, 102, 241]);
    y = section.y;

    doc.setFontSize(8);
    doc.setFont(FONTS.regular, 'normal');
    doc.setTextColor(COLORS.gray800[0], COLORS.gray800[1], COLORS.gray800[2]);

    const kwText = optimizedResume.addedKeywords.join('  \u2022  ');
    const lines = doc.splitTextToSize(kwText, CONTENT_WIDTH - 4);
    lines.forEach((line: string) => {
      y = checkPage(doc, y, 5);
      doc.text(line, MARGIN + 2, y);
      y += 5;
    });
    y += 2;
  }

  // ===== STRENGTHS =====
  if (results.strengths.length > 0) {
    const section = addSectionHeader(doc, y, 'Strengths', COLORS.green);
    y = section.y;

    results.strengths.forEach((strength) => {
      y = addBullet(doc, y, strength, { color: COLORS.gray700, fontSize: 9 });
    });
    y += 1;
  }

  // ===== AREAS TO IMPROVE =====
  if (results.improvements.length > 0) {
    const section = addSectionHeader(doc, y, 'Areas to Improve', COLORS.accent);
    y = section.y;

    results.improvements.forEach((improvement) => {
      y = addBullet(doc, y, improvement, { color: COLORS.gray700, fontSize: 9 });
    });
    y += 1;
  }

  // ===== OPTIMIZATION IMPROVEMENTS =====
  if (optimizedResume?.improvements && optimizedResume.improvements.length > 0) {
    const section = addSectionHeader(doc, y, 'Optimization Improvements', [16, 185, 129]);
    y = section.y;

    optimizedResume.improvements.forEach((improvement) => {
      y = addBullet(doc, y, improvement, { color: COLORS.gray700, fontSize: 9 });
    });
    y += 1;
  }

  // ===== REWRITTEN BULLETS =====
  if (optimizedResume?.rewrittenBullets && optimizedResume.rewrittenBullets.length > 0) {
    const section = addSectionHeader(doc, y, 'Bullet Point Rewrites', COLORS.orange);
    y = section.y;

    optimizedResume.rewrittenBullets.slice(0, 10).forEach((rb) => {
      y = checkPage(doc, y, 25);

      doc.setFillColor(COLORS.redLight[0], COLORS.redLight[1], COLORS.redLight[2]);
      doc.roundedRect(MARGIN, y, CONTENT_WIDTH, 1, 2, 2, 'F');
      y += 2;

      doc.setFontSize(7);
      doc.setFont(FONTS.bold, 'bold');
      doc.setTextColor(COLORS.red[0], COLORS.red[1], COLORS.red[2]);
      doc.text('BEFORE:', MARGIN + 3, y);
      y += 4;

      doc.setFont(FONTS.regular, 'normal');
      doc.setTextColor(COLORS.gray600[0], COLORS.gray600[1], COLORS.gray600[2]);
      doc.setFontSize(8);
      const origLines = doc.splitTextToSize(rb.original, CONTENT_WIDTH - 10);
      origLines.forEach((line: string) => {
        doc.text(line, MARGIN + 8, y);
        y += 4;
      });
      y += 1;

      doc.setFillColor(COLORS.greenLight[0], COLORS.greenLight[1], COLORS.greenLight[2]);
      doc.roundedRect(MARGIN, y, CONTENT_WIDTH, 1, 2, 2, 'F');
      y += 2;

      doc.setFontSize(7);
      doc.setFont(FONTS.bold, 'bold');
      doc.setTextColor(COLORS.green[0], COLORS.green[1], COLORS.green[2]);
      doc.text('AFTER:', MARGIN + 3, y);
      y += 4;

      doc.setFontSize(8);
      doc.setFont(FONTS.regular, 'normal');
      doc.setTextColor(COLORS.gray800[0], COLORS.gray800[1], COLORS.gray800[2]);
      const optLines = doc.splitTextToSize(rb.optimized, CONTENT_WIDTH - 10);
      optLines.forEach((line: string) => {
        doc.text(line, MARGIN + 8, y);
        y += 4;
      });

      y += 1;
      doc.setFontSize(6.5);
      doc.setFont(FONTS.italic, 'italic');
      doc.setTextColor(COLORS.gray500[0], COLORS.gray500[1], COLORS.gray500[2]);
      const reasonLines = doc.splitTextToSize(`Why: ${rb.reason}`, CONTENT_WIDTH - 10);
      reasonLines.forEach((line: string) => {
        doc.text(line, MARGIN + 8, y);
        y += 3;
      });
      y += 3;
    });
  }

  // ===== RECOMMENDATIONS =====
  const recSection = addSectionHeader(doc, y, 'Recommendations', COLORS.primary);
  y = recSection.y;

  const recommendations: string[] = [
    'Incorporate missing skills naturally throughout your resume experience section',
    'Use keywords from the job description in your bullet points',
    'Ensure clean, ATS-friendly formatting (avoid tables, columns, graphics)',
    'Quantify achievements with specific metrics and numbers',
    'Lead bullet points with strong action verbs (achieved, implemented, optimized)',
  ];

  if (optimizedResume?.analysis) {
    if (optimizedResume.analysis.weakBullets.length > 0) {
      recommendations.push('Strengthen remaining weak bullet points with more impact-focused language');
    }
    if (optimizedResume.analysis.duplicateKeywords.length > 0) {
      recommendations.push('Reduce keyword repetition to avoid ATS keyword stuffing penalties');
    }
    if (optimizedResume.analysis.sectionCompleteness &&
        Object.values(optimizedResume.analysis.sectionCompleteness).some(v => !v)) {
      recommendations.push('Complete all resume sections for maximum ATS scoring potential');
    }
  }

  recommendations.forEach((rec) => {
    y = addBullet(doc, y, rec, { color: COLORS.gray700, fontSize: 9 });
  });

  // Footers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages, 'ATS Resume Analyzer - Analysis Report');
  }

  const suffix = optimizedResume ? `_Optimized_${optimizationMode || 'ai'}` : '';
  const fileName = `ATS_Analysis_Report${suffix}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}

// ============================================================
// PDF 3: BEFORE vs AFTER COMPARISON PDF
// ============================================================

export function generateComparisonPDF(
  originalResumeText: string,
  optimizedResume: OptimizedResume,
  originalScore: number,
  mode: string = 'balanced'
) {
  const doc = createDoc();
  let y = MARGIN;

  const LEFT_X = MARGIN;
  const RIGHT_X = PAGE_WIDTH / 2 + 5;
  const COL_WIDTH = PAGE_WIDTH / 2 - MARGIN - 8;

  // ===== HEADER =====
  doc.setFillColor(COLORS.primaryDark[0], COLORS.primaryDark[1], COLORS.primaryDark[2]);
  doc.rect(0, 0, PAGE_WIDTH, 42, 'F');

  doc.setFillColor(COLORS.red[0], COLORS.red[1], COLORS.red[2]);
  doc.rect(0, 42, PAGE_WIDTH / 2, 2.5, 'F');

  doc.setFillColor(COLORS.green[0], COLORS.green[1], COLORS.green[2]);
  doc.rect(PAGE_WIDTH / 2, 42, PAGE_WIDTH / 2, 2.5, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont(FONTS.bold, 'bold');
  doc.text('Before vs After Optimization', PAGE_WIDTH / 2, 16, { align: 'center' });

  doc.setFontSize(8);
  doc.setFont(FONTS.regular, 'normal');
  const modeLabel = mode.charAt(0).toUpperCase() + mode.slice(1);
  doc.text(
    `Mode: ${modeLabel} | ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    PAGE_WIDTH / 2, 26, { align: 'center' }
  );

  doc.setFontSize(9);
  doc.setFont(FONTS.bold, 'bold');
  doc.setTextColor(255, 200, 200);
  doc.text(`Score: ${originalScore.toFixed(0)}/100`, PAGE_WIDTH / 4, 36, { align: 'center' });
  doc.setTextColor(200, 255, 200);
  doc.text(`Score: ${optimizedResume.predictedScore.toFixed(0)}/100`, (3 * PAGE_WIDTH) / 4, 36, { align: 'center' });

  doc.setFontSize(10);
  doc.setTextColor(255, 255, 200);
  doc.text(`+${optimizedResume.improvementPercentage.toFixed(0)}%`, PAGE_WIDTH / 2, 36, { align: 'center' });

  y = 50;

  // ===== SECTION HELPER FOR TWO-COLUMN LAYOUT =====
  const addComparisonSection = (
    title: string,
    leftContent: string,
    rightContent: string,
    options?: { fontSize?: number; fontWeight?: string }
  ) => {
    const fontSize = options?.fontSize || 8;
    const fontWeight = options?.fontWeight || 'normal';

    y = checkPage(doc, y, 15);
    doc.setFillColor(COLORS.gray100[0], COLORS.gray100[1], COLORS.gray100[2]);
    doc.rect(LEFT_X, y - 3, RIGHT_X + COL_WIDTH - LEFT_X, 8, 'F');

    doc.setFontSize(9);
    doc.setFont(FONTS.bold, 'bold');
    doc.setTextColor(COLORS.gray800[0], COLORS.gray800[1], COLORS.gray800[2]);
    doc.text(title, PAGE_WIDTH / 2, y + 2, { align: 'center' });
    y += 10;

    // Left column - Original
    y = checkPage(doc, y, 10);
    doc.setFontSize(7);
    doc.setFont(FONTS.bold, 'bold');
    doc.setTextColor(COLORS.red[0], COLORS.red[1], COLORS.red[2]);
    doc.text('ORIGINAL', LEFT_X, y);
    y += 4;

    doc.setFontSize(fontSize);
    doc.setFont(FONTS.regular, fontWeight);
    doc.setTextColor(COLORS.gray600[0], COLORS.gray600[1], COLORS.gray600[2]);
    const leftLines = doc.splitTextToSize(leftContent, COL_WIDTH - 2);
    leftLines.forEach((line: string) => {
      y = checkPage(doc, y, 4);
      doc.text(line, LEFT_X + 1, y);
      y += 4;
    });

    const leftEndY = y;

    // Right column - Optimized
    y = checkPage(doc, leftEndY, 10);
    doc.setFontSize(7);
    doc.setFont(FONTS.bold, 'bold');
    doc.setTextColor(COLORS.green[0], COLORS.green[1], COLORS.green[2]);
    doc.text('OPTIMIZED', RIGHT_X, y);
    y += 4;

    doc.setFontSize(fontSize);
    doc.setFont(FONTS.regular, fontWeight);
    doc.setTextColor(COLORS.gray800[0], COLORS.gray800[1], COLORS.gray800[2]);
    const rightLines = doc.splitTextToSize(rightContent, COL_WIDTH - 2);
    rightLines.forEach((line: string) => {
      y = checkPage(doc, y, 4);
      doc.text(line, RIGHT_X + 1, y);
      y += 4;
    });

    const rightEndY = y;
    y = Math.max(leftEndY, rightEndY) + 3;
    y = addDivider(doc, y, COLORS.gray200);
    y += 3;

    return y;
  };

  // Professional Summary
  if (optimizedResume.professionalSummary) {
    const origSummary = originalResumeText ? originalResumeText.substring(0, 500) : 'Original resume text not available';
    y = addComparisonSection('Professional Summary', origSummary, optimizedResume.professionalSummary, { fontSize: 8 });
  }

  // Skills
  if (optimizedResume.skills.length > 0) {
    const origSkills = originalResumeText
      ? originalResumeText.substring(0, 300)
      : 'Skills not extracted from original';
    const optSkills = optimizedResume.skills.join(', ');
    y = addComparisonSection(`Skills (${optimizedResume.skills.length} total)`, origSkills, optSkills, { fontSize: 8 });
  }

  // Experience Entries
  if (optimizedResume.experience.length > 0) {
    optimizedResume.experience.forEach((exp: ExperienceEntry) => {
      const optExpText = `${exp.title} at ${exp.company}\n${exp.dates}${exp.location ? ` | ${exp.location}` : ''}\n${exp.bullets.map(b => `\u2022 ${b}`).join('\n')}`;
      const origExpText = originalResumeText
        ? originalResumeText.substring(0, 500)
        : 'Original experience not available';

      y = addComparisonSection(
        `Experience: ${exp.title} at ${exp.company}`,
        origExpText, optExpText, { fontSize: 7.5 }
      );
    });
  }

  // Bullet Point Rewrites
  if (optimizedResume.rewrittenBullets.length > 0) {
    const rbTitle = addSectionHeader(doc, y, 'Bullet Point Improvements', COLORS.orange);
    y = rbTitle.y;

    optimizedResume.rewrittenBullets.slice(0, 12).forEach((rb) => {
      y = checkPage(doc, y, 20);

      doc.setFillColor(255, 247, 237);
      doc.rect(LEFT_X, y - 2, CONTENT_WIDTH, 7, 'F');
      doc.setFontSize(7);
      doc.setFont(FONTS.bold, 'bold');
      doc.setTextColor(COLORS.orange[0], COLORS.orange[1], COLORS.orange[2]);
      doc.text('Improvement', MARGIN + 3, y + 2);
      y += 8;

      // Original (left)
      doc.setFontSize(7);
      doc.setFont(FONTS.bold, 'bold');
      doc.setTextColor(COLORS.red[0], COLORS.red[1], COLORS.red[2]);
      doc.text('BEFORE:', LEFT_X, y);
      y += 3;

      doc.setFontSize(7.5);
      doc.setFont(FONTS.regular, 'normal');
      doc.setTextColor(COLORS.gray600[0], COLORS.gray600[1], COLORS.gray600[2]);
      const origLines = doc.splitTextToSize(rb.original, COL_WIDTH - 2);
      origLines.forEach((line: string) => {
        y = checkPage(doc, y, 3.5);
        doc.text(line, LEFT_X + 1, y);
        y += 3.5;
      });
      const leftY = y;

      // Optimized (right)
      y = Math.max(y - (origLines.length * 3.5), y - 20);
      doc.setFontSize(7);
      doc.setFont(FONTS.bold, 'bold');
      doc.setTextColor(COLORS.green[0], COLORS.green[1], COLORS.green[2]);
      doc.text('AFTER:', RIGHT_X, y);
      y += 3;

      doc.setFontSize(7.5);
      doc.setFont(FONTS.regular, 'normal');
      doc.setTextColor(COLORS.gray800[0], COLORS.gray800[1], COLORS.gray800[2]);
      const optLines = doc.splitTextToSize(rb.optimized, COL_WIDTH - 2);
      optLines.forEach((line: string) => {
        y = checkPage(doc, y, 3.5);
        doc.text(line, RIGHT_X + 1, y);
        y += 3.5;
      });
      const rightY = y;
      y = Math.max(leftY, rightY) + 2;

      // Reason
      doc.setFontSize(6.5);
      doc.setFont(FONTS.italic, 'italic');
      doc.setTextColor(COLORS.gray500[0], COLORS.gray500[1], COLORS.gray500[2]);
      const reasonLines = doc.splitTextToSize(`Why: ${rb.reason}`, CONTENT_WIDTH - 4);
      reasonLines.forEach((line: string) => {
        y = checkPage(doc, y, 3);
        doc.text(line, MARGIN + 2, y);
        y += 3;
      });

      y += 4;
      y = addDivider(doc, y, COLORS.gray200);
      y += 2;
    });
  }

  // ===== KEYWORDS & METRICS SUMMARY =====
  const summarySection = addSectionHeader(doc, y, 'Optimization Summary', COLORS.accent);
  y = summarySection.y;

  doc.setFontSize(9);
  doc.setFont(FONTS.bold, 'bold');
  doc.setTextColor(COLORS.gray800[0], COLORS.gray800[1], COLORS.gray800[2]);
  doc.text('Score:', LEFT_X, y);
  doc.setFont(FONTS.regular, 'normal');
  doc.setTextColor(COLORS.red[0], COLORS.red[1], COLORS.red[2]);
  doc.text(`${originalScore.toFixed(0)}/100`, LEFT_X + 20, y);
  doc.setTextColor(COLORS.gray500[0], COLORS.gray500[1], COLORS.gray500[2]);
  doc.text('\u2192', LEFT_X + 40, y);
  doc.setTextColor(COLORS.green[0], COLORS.green[1], COLORS.green[2]);
  doc.text(`${optimizedResume.predictedScore.toFixed(0)}/100`, LEFT_X + 50, y);
  doc.setTextColor(COLORS.accent[0], COLORS.accent[1], COLORS.accent[2]);
  doc.setFont(FONTS.bold, 'bold');
  doc.text(`+${optimizedResume.improvementPercentage.toFixed(0)}%`, LEFT_X + 75, y);
  y += 7;

  const metricsSummary = [
    `Keywords Added: ${optimizedResume.addedKeywords.length}`,
    `Bullets Rewritten: ${optimizedResume.rewrittenBullets.length}`,
    `Keyword Density: ${optimizedResume.analysis.keywordDensity.toFixed(1)}%`,
    `Action Verb Score: ${optimizedResume.analysis.actionVerbScore.toFixed(0)}%`,
  ];

  metricsSummary.forEach((metric) => {
    doc.setFontSize(8);
    doc.setFont(FONTS.regular, 'normal');
    doc.setTextColor(COLORS.gray700[0], COLORS.gray700[1], COLORS.gray700[2]);
    doc.text(`\u2022 ${metric}`, LEFT_X + 2, y);
    y += 4.5;
  });

  // Footers
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc, i, totalPages, 'ATS Resume Analyzer - Before vs After Comparison');
  }

  const fileName = `before-after-comparison-${mode}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
}

// ============================================================
// COMPATIBILITY LAYER
// ============================================================

export function generatePDF(options: { results: AnalysisResult; optimizedResume?: OptimizedResume; optimizationMode?: string } | AnalysisResult) {
  let results: AnalysisResult;
  let optimizedResume: OptimizedResume | undefined;
  let optimizationMode: string | undefined;

  if ('results' in options) {
    const opts = options as { results: AnalysisResult; optimizedResume?: OptimizedResume; optimizationMode?: string };
    results = opts.results;
    optimizedResume = opts.optimizedResume;
    optimizationMode = opts.optimizationMode;
  } else {
    results = options as AnalysisResult;
  }

  generatePDFReport(results, optimizedResume, optimizationMode);
}